---
name: Class-DBI-ViewLoader
version: 0.05
author:
  - 'Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>'
abstract: |-
  Load views from existing databases as Class::DBI
  classes
license: perl
requires:
  Class::DBI: 0
  DBI: 1.43
  Module::Pluggable: 0
  version: 0
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
build_requires:
  DBD::Mock: 0.22
  Test::More: 0
provides:
  Class::DBI::ViewLoader:
    file: lib/Class/DBI/ViewLoader.pm
    version: 0.05
  Class::DBI::ViewLoader::Auto:
    file: lib/Class/DBI/ViewLoader/Auto.pm
    version: 0.01
generated_by: Module::Build version 0.2611
